### ISSUE TITLE
MapLoading - Possible Bug when selecting "Garbage" Map

### ISSUE THREAD

**Issue by derkanadier** [Swess/RiskGame#15]
When I was trying to play around with the penultimate master release, if I selected the garbage map in the list it would correctly display an error message in console stating that the file does not exist / is incorrect. However when prompted to select a different map file, we are probably not resetting the map file location: when selecting a valid map, the console would still output the 'inexistent' file error.

**Comment by Kerry-G** [comment]
https://github.com/Swess/RiskGame/pull/16
